name: subtracker
description: A subscription tracking app built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Routing
  go_router: ^13.1.0

  # Utils
  intl: ^0.18.1
  uuid: ^4.3.3

  # UI
  flutter_slidable: ^3.0.1
  google_fonts: ^6.1.0

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  very_good_analysis: ^5.1.0

  # Code Generation
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
